### ISSUE TITLE
any reason to not publish test file to npm ?

### ISSUE THREAD

**Issue by huang47** [sindresorhus/object-assign#11]
I am using 2.0.0 and a bit curious about why there is no test file attached since it's already in github repo

Any insights?

**Comment by arthurvr** [comment]
What would be the advantage of having the tests in?

**Comment by huang47** [comment]
to make the users feel more comfortable to know it's working?

For example: now I am using object-assign and need to know if it's passing all unit tests. I have to pull this github repo and run tests. And I have to run it every time object-assign bumps version.

**Comment by arthurvr** [comment]
@huang47 That's why we add the Travis CI badge to the readme ;)

**Comment by huang47** [comment]
ahha, good point ! Thanks for the explanation :+1:

**Comment by arthurvr** [comment]
@huang47 You're welcome!
