### ISSUE TITLE
"main" in manifest

### ISSUE THREAD

**Issue by NekR** [sindresorhus/object-assign#19]
I know it works fine on npm without "main" field in package.json, but it may fail in other enviroments as did in NativeScript (https://github.com/NativeScript/NativeScript/issues/466). I understand what that is a NativeScript bug, but is it a problem to add "main" fields to the package.json?

**Comment by arthurvr** [comment]
It's npm-wise valid and as you mentioned yourself a NativeScript bug. None of our business, thus :) Just updating one package.json isn't a big deal indeed, but updating hunderds of modules would be.

**Comment by NekR** [comment]
@arthurvr that is true and I agree, but problem is that NativeScript does not makes releases too often, so it's easier to fix concrete package.
