### ISSUE TITLE
Add browser support 

### ISSUE THREAD

**Issue by tinacious** [sindresorhus/object-assign#29]
Exception thrown because `module` is undefined in the browser.

**Comment by tinacious** [comment]
Related PR with fix: https://github.com/sindresorhus/object-assign/pull/28

**Comment by shinnn** [comment]
Please check the existing issues before opening a new issue or creating a pull request. https://github.com/sindresorhus/object-assign/pull/27

**Comment by tinacious** [comment]
That's unfortunate that there are no intentions to make this work in the browser, considering the package is offered on Bower.
