### ISSUE TITLE
Aliasing object functions

### ISSUE THREAD

**Issue by Jameskmonger** [sindresorhus/object-assign#31]
Hi @sindresorhus,

What's the reason for aliasing these two object functions:

```javascript
var hasOwnProperty = Object.prototype.hasOwnProperty;
var propIsEnumerable = Object.prototype.propertyIsEnumerable;
```

And then calling them like `hasOwnProperty.call(from, key)`.

Why not just use `from.hasOwnProperty(key)`?

**Comment by SamVerschueren** [comment]
You can't know for sure that `from` has a prototype or the method could as well be overridden.

**Comment by sindresorhus** [comment]
To protect about objects without a prototype. You should really always do this when dealing with external objects.

```js
const x = Object.create(null);

x.foo = true;

console.log(x.hasOwnProperty('foo'));
//=> Uncaught TypeError: x.hasOwnProperty is not a function(…)
```
