### ISSUE TITLE
[Question] Some sort of policy for peaces in shouldUseNative func

### ISSUE THREAD

**Issue by btd** [sindresorhus/object-assign#36]
Hi, there.

I am just curious do you have any sort of policy for removing peaces of checks in shouldUseNative. I looked in bugs urls from comments, and last update to bugs was Dec 2015 - that is why i am curious if such checks still required. 

Thanks.

**Comment by SamVerschueren** [comment]
I don't really get your comment. Why should some checks be removed? It was added for a [reason](https://github.com/sindresorhus/object-assign/pull/32).

**Comment by btd** [comment]
Ok, got it (that is why it marked as [Question], i am not suggesting to remove anything).
