### ISSUE TITLE
React isn't citing your licence

### ISSUE THREAD

**Issue by markalanrichards** [sindresorhus/object-assign#44]
Your library is included in React, good job, but Facebook aren't boasting about your project being included, as your MIT licence choice suggests you would like.

So I'm asking them fix it, but thought you should know.

https://markssoftware.com/2017/01/14/npm-is-lying-to-you-and-facebook-is-stealing-copyright/

**Comment by sindresorhus** [comment]
Don't care. Sorry. I make software to share with the world, not for the credit. I hereby give Facebook and anyone the right to use this code for anything without any credit or license inclusion.

**Comment by markalanrichards** [comment]
That is great, but because you already have a licence and commits from
contributors: would all contributors need to make the same declaration?

I'm afraid it still doesn't mean Facebook can represent copyright ownership
of your part in their product, which I fear is another problem in what they
may have done.


On 14 Jan 2017 20:39, "Sindre Sorhus" <notifications@github.com> wrote:

Don't care. Sorry. I make software to share with the world, not for the
credit. I hereby give Facebook and anyone the right to use this code for
anything without any credit or license inclusion.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sindresorhus/object-assign/issues/44#issuecomment-272651383>,
or mute the thread
